# Generated by Django 4.1.5 on 2023-04-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
