# Generated by Django 4.1.5 on 2023-04-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expensecategory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomecategory',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
