# Generated by Django 4.1.5 on 2023-04-23 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_incomecategory_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomecategory',
            old_name='is_main',
            new_name='is_important',
        ),
    ]
