# Generated by Django 4.1.5 on 2023-04-23 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_rename_is_main_incomecategory_is_important'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='created_at',
        ),
        migrations.AddField(
            model_name='income',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
