# Generated by Django 4.1.5 on 2023-04-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_remove_income_created_at_income_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
