# Generated by Django 4.1.5 on 2023-04-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_rename_created_at_savingcategory_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingcategory',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
