# Generated by Django 4.1.5 on 2023-04-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_alter_savingcategory_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField()),
                ('total_expenses', models.IntegerField()),
            ],
        ),
    ]
