# Generated by Django 4.1.5 on 2023-04-30 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_weeklyexpense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyexpense',
            old_name='week',
            new_name='week_date',
        ),
    ]
