# Generated by Django 4.1.5 on 2023-07-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='created_at',
            field=models.DateField(),
        ),
    ]
