# Generated by Django 4.1.5 on 2023-07-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_alter_saving_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
